# Generated by Django 4.2.6 on 2024-04-10 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reminder", "0002_alter_task_assigned_by_alter_task_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assigned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="item_assigned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
