# Generated by Django 4.2.6 on 2024-04-07 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eDiary", "0004_noteshistory_signup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="signup",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eDiary.signup",
            ),
        ),
        migrations.AlterField(
            model_name="notes",
            name="signup",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eDiary.signup",
            ),
        ),
        migrations.AlterField(
            model_name="noteshistory",
            name="note",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eDiary.notes",
            ),
        ),
    ]
