# Generated by Django 4.2.6 on 2024-04-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eDiary", "0006_alter_notes_category_alter_noteshistory_signup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="mobileNumber",
            field=models.CharField(max_length=13, null=True),
        ),
    ]
